name: CI - Backend RentSecure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: rentsecure_ci
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ci" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      FLYWAY_URL: jdbc:postgresql://localhost:5432/rentsecure_ci
      FLYWAY_USER: ci
      FLYWAY_PASSWORD: ci_pass

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache local de Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Dar permisos de ejecución a mvnw
      run: chmod +x ./mvnw

    - name: Ejecutar tests unitarios
      run: ./mvnw --batch-mode clean test

    - name: Ejecutar migraciones Flyway en Postgres CI
      run: |
        ./mvnw --batch-mode \
          -Dflyway.url=$FLYWAY_URL \
          -Dflyway.user=$FLYWAY_USER \
          -Dflyway.password=$FLYWAY_PASSWORD \
          flyway:migrate

    - name: Validar integridad de migraciones Flyway
      run: |
        ./mvnw --batch-mode \
          -Dflyway.url=$FLYWAY_URL \
          -Dflyway.user=$FLYWAY_USER \
          -Dflyway.password=$FLYWAY_PASSWORD \
          flyway:validate