name: CI - Backend RentSecure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: rentsecure_ci
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ci"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # 🐘 Flyway (usado antes de correr los tests)
      FLYWAY_URL: jdbc:postgresql://localhost:5432/rentsecure_ci
      FLYWAY_USER: ci
      FLYWAY_PASSWORD: ci_pass

      # Perfil de tests
      SPRING_PROFILES_ACTIVE: test   # <-- tu AuthFlowIT usa @ActiveProfiles("test")

    steps:
    # 1. Checkout
    - name: Checkout código
      uses: actions/checkout@v3

    # 2. JDK 21
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. Cache Maven
    - name: Cache local de Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # 4. Permisos para mvnw
    - name: Dar permisos de ejecución a mvnw
      run: chmod +x ./mvnw

    # 5. Migraciones Flyway (crea el esquema para los tests)
    - name: Ejecutar migraciones Flyway en Postgres CI
      run: |
        ./mvnw --batch-mode \
          -Dflyway.url=$FLYWAY_URL \
          -Dflyway.user=$FLYWAY_USER \
          -Dflyway.password=$FLYWAY_PASSWORD \
          flyway:migrate

    # 6. Suite completa: unit + integration tests
    - name: Ejecutar suite de tests (unit + IT)
      run: ./mvnw --batch-mode clean verify

    # 7. Validar integridad Flyway (opcional, asegura que nadie cambió migraciones ya aplicadas)
    - name: Validar integridad de migraciones Flyway
      run: |
        ./mvnw --batch-mode \
          -Dflyway.url=$FLYWAY_URL \
          -Dflyway.user=$FLYWAY_USER \
          -Dflyway.password=$FLYWAY_PASSWORD \
          flyway:validate